import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lighBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import TransitionEffect from '@/components/TransitionEffect';


export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center  text-dark w-full min-h-screen ' >

        <Layout className='pt-0 md:pt-16 sm:pt-8'>

          <div className="flex items-center justify-between w-full lg:flex-col ">

            <div className='w-[50%] md:w-full '>
                <Image src={ProfilePic} alt="simranmansoori" className='w-[70%] h-auto lg:hidden md:inline-block md:w-full' priority 
                sizes='(max-width: 768px) 1000vw, (max-width: 1200px) 50vw 50vw' />
            </div>

            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'> 
                <AnimatedText text="Turning Vision Into Reality With Code And Design." 
                className='!text-5xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
                <p className='py-4 text-xl font-medium md:text-sm sm:text-xs'>As a skilled web developer, I am dedicated to turning ideas into innovative web applications. 

                  Explore my latest projects. Showcasing my expertise web development.
                </p>

              <div className='flex items-center self-start mt-2 lg:self-center '>
                <Link href="/dummy.pdf" target={"_blank"} 
                  className='flex items-center bg-dark text-light rounded-lg p-2.5 px-6  text-lg font-semibold
                hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base  '
                  download={true}
                  >Resume <LinkArrow className={'w-6 ml-1 md:w-4 sm:w-3'} />
                </Link >
                <Link href="mailto:simranmansoori1996@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium text-dark underline md:text-base'>Contact</Link>
              </div>
            </div>
          </div>

        </Layout>

        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-20 md:hidden'>
          <Image src={lighBulb} alt='codebucks' className='w-full h-auto'  />
        </div> 
      </main>
    </>
  )
}
